import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { createClient } from '@supabase/supabase-js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// 1. Data 1 - 35 (Data Awal yang sudah ada)
import { initialSuratList as existing35 } from '../src/data/initialSuratData.js'

// 2. Data 36 - 100 (65 Data Tambahan Realistis Perbankan Palembang)
const additionalData = [
  {
    id: 'SURAT-036',
    nama: 'Hendra Wijaya (CV Musi Baja Perkasa)',
    tahun: '2023',
    sp1: '14-Feb-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - HENDRA WIJAYA',
    lpjUrgent: false,
    pk: 'PK - HENDRA WIJAYA',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Angsuran lancar, SP 1 sebelumnya telah diselesaikan melalui restrukturisasi kredit.'
  },
  {
    id: 'SURAT-037',
    nama: 'Dewi Anggraini (Toko Pakaian Cantika)',
    tahun: '2024',
    sp1: '10-Mar-24',
    sp1Urgent: true,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - DEWI ANGGRAINI',
    lpjUrgent: false,
    pk: 'PK - DEWI ANGGRAINI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 dikirimkan ke alamat toko Pasar 16 Ilir. Menunggu konfirmasi pembayaran.'
  },
  {
    id: 'SURAT-038',
    nama: 'Kurniawan Saputra (Bengkel Las Kurnia)',
    tahun: '2022',
    sp1: '05-Jan-22',
    sp1Urgent: false,
    sp2: '20-Feb-22',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - KURNIAWAN SAPUTRA',
    lpjUrgent: false,
    pk: 'PK - KURNIAWAN SAPUTRA',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Debitur berjanji melunasi tunggakan bunga setelah pencairan proyek bengkel.'
  },
  {
    id: 'SURAT-039',
    nama: 'PT Sriwijaya Logistik Nusantara',
    tahun: '2025',
    sp1: '12-Jan-25',
    sp1Urgent: false,
    sp2: '18-Feb-25',
    sp2Urgent: false,
    sp3: '22-Mar-25',
    sp3Urgent: true,
    spDefault: '15-Apr-25',
    spDefaultUrgent: true,
    lpj: 'LPJ - PT SRIWIJAYA LOGISTIK',
    lpjUrgent: true,
    pk: 'PK - PT SRIWIJAYA LOGISTIK',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'Status SP Default, agunan gudang logistik sedang dalam proses appraisal ulang oleh tim penilai.'
  },
  {
    id: 'SURAT-040',
    nama: 'Siti Aminah (Warung Kopi & Sarapan Pagi)',
    tahun: '2023',
    sp1: '19-May-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - SITI AMINAH',
    lpjUrgent: false,
    pk: 'PK - SITI AMINAH',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Mantri telah melakukan kunjungan on the spot (OTS) ke lokasi usaha warung.'
  },
  {
    id: 'SURAT-041',
    nama: 'Ferry Ardiansyah (Toko Elektronik Surya)',
    tahun: '2024',
    sp1: '02-Feb-24',
    sp1Urgent: false,
    sp2: '15-Mar-24',
    sp2Urgent: false,
    sp3: '20-Apr-24',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - FERRY ARDIANSYAH',
    lpjUrgent: false,
    pk: 'PK - FERRY ARDIANSYAH',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'Surat Peringatan 3 telah diterima langsung oleh yang bersangkutan, mediasi dijadwalkan pekan depan.'
  },
  {
    id: 'SURAT-042',
    nama: 'CV Bukit Asam Distribusi',
    tahun: '2022',
    sp1: '11-Jun-22',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV BUKIT ASAM',
    lpjUrgent: false,
    pk: 'PK - CV BUKIT ASAM',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Fasilitas kredit berjalan lancar, berkas PK dan LPJ lengkap di lemari arsip 2.'
  },
  {
    id: 'SURAT-043',
    nama: 'Nurul Hidayati (Klinik & Apotek Sehat)',
    tahun: '2025',
    sp1: '08-Jan-25',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - NURUL HIDAYATI',
    lpjUrgent: false,
    pk: 'PK - NURUL HIDAYATI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Keterlambatan pembayaran akibat kendala klaim BPJS klinik. Terbit SP 1.'
  },
  {
    id: 'SURAT-044',
    nama: 'Agus Setiawan (Perkebunan Sawit Mandiri)',
    tahun: '2023',
    sp1: '16-Aug-23',
    sp1Urgent: false,
    sp2: '21-Sep-23',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - AGUS SETIAWAN',
    lpjUrgent: false,
    pk: 'PK - AGUS SETIAWAN',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Tahap SP 2. Hasil panen kebun sawit menurun, debitur mengajukan restrukturisasi penurunan bunga.'
  },
  {
    id: 'SURAT-045',
    nama: 'Dian Permatasari (Boutique Hijab Palembang)',
    tahun: '2024',
    sp1: '03-Jan-24',
    sp1Urgent: false,
    sp2: '14-Feb-24',
    sp2Urgent: false,
    sp3: '19-Mar-24',
    sp3Urgent: false,
    spDefault: '25-Apr-24',
    spDefaultUrgent: true,
    lpj: 'LPJ - DIAN PERMATASARI',
    lpjUrgent: false,
    pk: 'PK - DIAN PERMATASARI',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'Debitur wanprestasi, SP Default telah diserahkan ke bagian hukum kantor wilayah BRI.'
  },
  {
    id: 'SURAT-046',
    nama: 'M. Ridwan Hakim (UD Mitra Tani Makmur)',
    tahun: '2022',
    sp1: '28-Oct-22',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - M RIDWAN HAKIM',
    lpjUrgent: false,
    pk: 'PK - M RIDWAN HAKIM',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Tunggakan 1 bulan, debitur menyatakan siap melunasi setelah panen jagung.'
  },
  {
    id: 'SURAT-047',
    nama: 'PT Jakabaring Prima Properti',
    tahun: '2025',
    sp1: '15-Feb-25',
    sp1Urgent: false,
    sp2: '20-Mar-25',
    sp2Urgent: true,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT JAKABARING PROPERTI',
    lpjUrgent: true,
    pk: 'PK - PT JAKABARING PROPERTI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Perusahaan perumahan, perlu pengecekan berkas LPJ fisik dan sertifikat induk agunan.'
  },
  {
    id: 'SURAT-048',
    nama: 'Eka Prasetya (Penyedia Alat Tulis Kantor)',
    tahun: '2023',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - EKA PRASETYA',
    lpjUrgent: false,
    pk: 'PK - EKA PRASETYA',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Nasabah kooperatif dan pembayaran selalu tepat waktu via autodebet rekening BRI.'
  },
  {
    id: 'SURAT-049',
    nama: 'Rina Wulandari (Toko Emas Semar Jaya)',
    tahun: '2024',
    sp1: '07-Jul-24',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - RINA WULANDARI',
    lpjUrgent: false,
    pk: 'PK - RINA WULANDARI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 diterbitkan sebagai pengingat jatuh tempo masa tenggang bunga.'
  },
  {
    id: 'SURAT-050',
    nama: 'Bambang Irawan (Penggilingan Padi Berkah)',
    tahun: '2022',
    sp1: '12-May-22',
    sp1Urgent: false,
    sp2: '16-Jun-22',
    sp2Urgent: false,
    sp3: '22-Jul-22',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - BAMBANG IRAWAN',
    lpjUrgent: false,
    pk: 'PK - BAMBANG IRAWAN',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'Surat Peringatan 3. Debitur meminta penundaan lelang dan siap mencari pembeli mandiri.'
  },
  {
    id: 'SURAT-051',
    nama: 'CV Demang Lebar Transport',
    tahun: '2025',
    sp1: '10-Jan-25',
    sp1Urgent: false,
    sp2: '14-Feb-25',
    sp2Urgent: false,
    sp3: '18-Mar-25',
    sp3Urgent: false,
    spDefault: '22-Apr-25',
    spDefaultUrgent: true,
    lpj: 'LPJ - CV DEMANG LEBAR',
    lpjUrgent: true,
    pk: 'PK - CV DEMANG LEBAR',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default, 5 unit armada dump truck dijadikan jaminan fidusia dan telah diverifikasi.'
  },
  {
    id: 'SURAT-052',
    nama: 'Iskandar Muda (Toko Sepatu & Tas Barokah)',
    tahun: '2023',
    sp1: '05-Sep-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - ISKANDAR MUDA',
    lpjUrgent: false,
    pk: 'PK - ISKANDAR MUDA',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Debitur mengajukan permohonan keringanan denda keterlambatan.'
  },
  {
    id: 'SURAT-053',
    nama: 'Yuliana Sari (Apotek Kimia Mandiri)',
    tahun: '2024',
    sp1: '11-Nov-24',
    sp1Urgent: false,
    sp2: '15-Dec-24',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - YULIANA SARI',
    lpjUrgent: false,
    pk: 'PK - YULIANA SARI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'SP 2 diserahkan langsung oleh Account Officer. Dijanjikan angsuran masuk akhir pekan.'
  },
  {
    id: 'SURAT-054',
    nama: 'PT Ampera Graha Konstruksi',
    tahun: '2022',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT AMPERA GRAHA',
    lpjUrgent: false,
    pk: 'PK - PT AMPERA GRAHA',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Kredit investasi konstruksi lancar, proyek jembatan dan jalan di Palembang Selatan.'
  },
  {
    id: 'SURAT-055',
    nama: 'Herman Susilo (Peternakan Ayam Broiler)',
    tahun: '2025',
    sp1: '04-Feb-25',
    sp1Urgent: true,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - HERMAN SUSILO',
    lpjUrgent: false,
    pk: 'PK - HERMAN SUSILO',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Kematian bibit ayam akibat cuaca ekstrem. Debitur sedang recovery siklus ternak baru.'
  },
  {
    id: 'SURAT-056',
    nama: 'Anita Rahayu (Toko Bahan Kue Delima)',
    tahun: '2023',
    sp1: '17-Apr-23',
    sp1Urgent: false,
    sp2: '22-May-23',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - ANITA RAHAYU',
    lpjUrgent: false,
    pk: 'PK - ANITA RAHAYU',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'SP 2 dikirim via ekspedisi tercatat, debitur telah menyetujui restrukturisasi pokok.'
  },
  {
    id: 'SURAT-057',
    nama: 'Doni Kusuma (Rental Mobil & Travel Palembang)',
    tahun: '2024',
    sp1: '09-Jun-24',
    sp1Urgent: false,
    sp2: '14-Jul-24',
    sp2Urgent: false,
    sp3: '19-Aug-24',
    sp3Urgent: false,
    spDefault: '25-Sep-24',
    spDefaultUrgent: true,
    lpj: 'LPJ - DONI KUSUMA',
    lpjUrgent: true,
    pk: 'PK - DONI KUSUMA',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default, unit kendaraan operasional travel dalam pengawasan pihak recovery aset.'
  },
  {
    id: 'SURAT-058',
    nama: 'CV Sukarami Steelindo',
    tahun: '2022',
    sp1: '14-Mar-22',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV SUKARAMI STEEL',
    lpjUrgent: false,
    pk: 'PK - CV SUKARAMI STEEL',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Tagihan piutang distributor belum cair. Berjanji menyelesaikan tagihan dalam 14 hari.'
  },
  {
    id: 'SURAT-059',
    nama: 'Lestari Indah (Toko Kosmetik Glow)',
    tahun: '2025',
    sp1: '02-Jan-25',
    sp1Urgent: false,
    sp2: '06-Feb-25',
    sp2Urgent: false,
    sp3: '12-Mar-25',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - LESTARI INDAH',
    lpjUrgent: false,
    pk: 'PK - LESTARI INDAH',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'Tahap SP 3, berkas agunan ruko di Ilir Barat II disiapkan untuk eksekusi lelang KPKNL.'
  },
  {
    id: 'SURAT-060',
    nama: 'Rahmat Hidayat (Pangkalan Gas LPG 3Kg)',
    tahun: '2023',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - RAHMAT HIDAYAT',
    lpjUrgent: false,
    pk: 'PK - RAHMAT HIDAYAT',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Omset stabil, debitur memenuhi kewajiban angsuran sebelum tanggal 10 setiap bulannya.'
  },
  {
    id: 'SURAT-061',
    nama: 'PT Ogan Ilir Agro Lestari',
    tahun: '2024',
    sp1: '18-Aug-24',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT OGAN ILIR AGRO',
    lpjUrgent: false,
    pk: 'PK - PT OGAN ILIR AGRO',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Keterlambatan transfer termin dari pembeli CPO. SP 1 sudah disampaikan ke direksi.'
  },
  {
    id: 'SURAT-062',
    nama: 'Fitri Handayani (Salon & Spa Muslimah)',
    tahun: '2022',
    sp1: '05-May-22',
    sp1Urgent: false,
    sp2: '10-Jun-22',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - FITRI HANDAYANI',
    lpjUrgent: false,
    pk: 'PK - FITRI HANDAYANI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Debitur bersedia menjual salah satu aset untuk menutupi tunggakan pinjaman di KCP.'
  },
  {
    id: 'SURAT-063',
    nama: 'Asep Saepullah (Percetakan & Sablon Digital)',
    tahun: '2025',
    sp1: '11-Jan-25',
    sp1Urgent: false,
    sp2: '15-Feb-25',
    sp2Urgent: false,
    sp3: '20-Mar-25',
    sp3Urgent: false,
    spDefault: '28-Apr-25',
    spDefaultUrgent: true,
    lpj: 'LPJ - ASEP SAEPULLAH',
    lpjUrgent: true,
    pk: 'PK - ASEP SAEPULLAH',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default disahkan, mesin percetakan digital dalam daftar sita jaminan.'
  },
  {
    id: 'SURAT-064',
    nama: 'CV Plaju Mandiri Energi',
    tahun: '2023',
    sp1: '25-Oct-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV PLAJU MANDIRI',
    lpjUrgent: false,
    pk: 'PK - CV PLAJU MANDIRI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 diterbitkan, debitur menyampaikan rencana pembayaran parsial tanggal 30.'
  },
  {
    id: 'SURAT-065',
    nama: 'Sri Wahyuni (Pusat Grosir Pakaian Pasar 16)',
    tahun: '2024',
    sp1: '12-Feb-24',
    sp1Urgent: false,
    sp2: '18-Mar-24',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - SRI WAHYUNI',
    lpjUrgent: false,
    pk: 'PK - SRI WAHYUNI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Pasar sepi pasca renovasi, debitur memohon restrukturisasi perpanjangan tenor 12 bulan.'
  },
  {
    id: 'SURAT-066',
    nama: 'Wahyu Pratama (Toko Meubel Jati Makmur)',
    tahun: '2022',
    sp1: '07-Sep-22',
    sp1Urgent: false,
    sp2: '12-Oct-22',
    sp2Urgent: false,
    sp3: '17-Nov-22',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - WAHYU PRATAMA',
    lpjUrgent: false,
    pk: 'PK - WAHYU PRATAMA',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'SP 3 telah terkirim. Mantri dan supervisor menjadwalkan peninjauan fisik agunan.'
  },
  {
    id: 'SURAT-067',
    nama: 'PT Kertapati Pelabuhan Logistik',
    tahun: '2025',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT KERTAPATI LOGISTIK',
    lpjUrgent: false,
    pk: 'PK - PT KERTAPATI LOGISTIK',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Kredit korporasi pelabuhan, performa finansial sangat sehat dan pembayaran tertib.'
  },
  {
    id: 'SURAT-068',
    nama: 'Indah Permata (Distributor Kopi Pagaralam)',
    tahun: '2023',
    sp1: '14-Jun-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - INDAH PERMATA',
    lpjUrgent: false,
    pk: 'PK - INDAH PERMATA',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 telah diterima. Debitur meminta waktu 1 minggu untuk pencairan giro pembeli.'
  },
  {
    id: 'SURAT-069',
    nama: 'Teguh Supriyanto (Toko Velg & Ban Mobil)',
    tahun: '2024',
    sp1: '04-May-24',
    sp1Urgent: false,
    sp2: '09-Jun-24',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - TEGUH SUPRIYANTO',
    lpjUrgent: false,
    pk: 'PK - TEGUH SUPRIYANTO',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Tunggakan 60 hari. Debitur diundang mediasi di BRI KCP Iskandar Palembang.'
  },
  {
    id: 'SURAT-070',
    nama: 'CV Ilir Barat Solusindo',
    tahun: '2022',
    sp1: '02-Feb-22',
    sp1Urgent: false,
    sp2: '08-Mar-22',
    sp2Urgent: false,
    sp3: '14-Apr-22',
    sp3Urgent: false,
    spDefault: '20-May-22',
    spDefaultUrgent: true,
    lpj: 'LPJ - CV ILIR BARAT',
    lpjUrgent: true,
    pk: 'PK - CV ILIR BARAT',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default aktif. Debitur menyerahkan agunan sukarela untuk lelang tertutup.'
  },
  {
    id: 'SURAT-071',
    nama: 'Desi Ratnasari (Rumah Makan Pindang Meranjat)',
    tahun: '2025',
    sp1: '20-Jan-25',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - DESI RATNASARI',
    lpjUrgent: false,
    pk: 'PK - DESI RATNASARI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 diberikan karena keterlambatan 15 hari. Rumah makan sedang renovasi dapur.'
  },
  {
    id: 'SURAT-072',
    nama: 'Rudi Hermawan (Grosir Sembako 88)',
    tahun: '2023',
    sp1: '08-Aug-23',
    sp1Urgent: false,
    sp2: '15-Sep-23',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - RUDI HERMAWAN',
    lpjUrgent: false,
    pk: 'PK - RUDI HERMAWAN',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Debitur mengajukan permohonan restrukturisasi jadwal angsuran musiman.'
  },
  {
    id: 'SURAT-073',
    nama: 'PT Musi Rawas Sawit Perkasa',
    tahun: '2024',
    sp1: '01-Nov-24',
    sp1Urgent: false,
    sp2: '05-Dec-24',
    sp2Urgent: false,
    sp3: '10-Jan-25',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT MUSI RAWAS SAWIT',
    lpjUrgent: false,
    pk: 'PK - PT MUSI RAWAS SAWIT',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'SP 3 telah dikirim ke kantor operasional. Debitur diminta hadir paling lambat 7 hari kerja.'
  },
  {
    id: 'SURAT-074',
    nama: 'Maya Safitri (Toko Optik Surya Cemerlang)',
    tahun: '2022',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - MAYA SAFITRI',
    lpjUrgent: false,
    pk: 'PK - MAYA SAFITRI',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Kredit usaha rakyat (KUR) mikro, catatan mutasi rekening koran sangat aktif.'
  },
  {
    id: 'SURAT-075',
    nama: 'Zulkifli Lubis (Depo Pasir & Bahan Bangunan)',
    tahun: '2025',
    sp1: '16-Feb-25',
    sp1Urgent: true,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - ZULKIFLI LUBIS',
    lpjUrgent: false,
    pk: 'PK - ZULKIFLI LUBIS',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Proyek perumahan yang dipasok terlambat bayar, debitur berjanji menyetor minggu depan.'
  },
  {
    id: 'SURAT-076',
    nama: 'CV Gandus Hijau Lestari',
    tahun: '2023',
    sp1: '12-Mar-23',
    sp1Urgent: false,
    sp2: '18-Apr-23',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV GANDUS HIJAU',
    lpjUrgent: false,
    pk: 'PK - CV GANDUS HIJAU',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'SP 2 telah diterima oleh direktur operasional CV. Janji bayar sebelum tanggal 25.'
  },
  {
    id: 'SURAT-077',
    nama: 'Nur Aini (Toko Mainan & Aksesoris Anak)',
    tahun: '2024',
    sp1: '05-May-24',
    sp1Urgent: false,
    sp2: '11-Jun-24',
    sp2Urgent: false,
    sp3: '16-Jul-24',
    sp3Urgent: false,
    spDefault: '22-Aug-24',
    spDefaultUrgent: true,
    lpj: 'LPJ - NUR AINI',
    lpjUrgent: true,
    pk: 'PK - NUR AINI',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default telah disetujui. Agunan berupa SHM rumah tinggal siap didaftarkan lelang.'
  },
  {
    id: 'SURAT-078',
    nama: 'Iwan Falsafah (Penyewaan Tenda & Pelaminan)',
    tahun: '2022',
    sp1: '19-Sep-22',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - IWAN FALSAFAH',
    lpjUrgent: false,
    pk: 'PK - IWAN FALSAFAH',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Kolektibilitas 2, telah dilakukan penagihan persuasif oleh Account Officer BRI.'
  },
  {
    id: 'SURAT-079',
    nama: 'PT Kemuning Abadi Sejahtera',
    tahun: '2025',
    sp1: '10-Feb-25',
    sp1Urgent: false,
    sp2: '15-Mar-25',
    sp2Urgent: true,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT KEMUNING ABADI',
    lpjUrgent: false,
    pk: 'PK - PT KEMUNING ABADI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Surat Peringatan 2 dikirim ke kantor perwakilan. Direktur berhalangan hadir karena luar kota.'
  },
  {
    id: 'SURAT-080',
    nama: 'Farida Hanum (Toko Kain Songket Palembang Asli)',
    tahun: '2023',
    sp1: '03-Jun-23',
    sp1Urgent: false,
    sp2: '08-Jul-23',
    sp2Urgent: false,
    sp3: '14-Aug-23',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - FARIDA HANUM',
    lpjUrgent: false,
    pk: 'PK - FARIDA HANUM',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'SP 3 aktif. Debitur memiliki stok songket senilai 300 juta yang sedang ditawarkan ke galeri.'
  },
  {
    id: 'SURAT-081',
    nama: 'Hadi Suwarno (Bengkel Bubut & Bubut Silinder)',
    tahun: '2024',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - HADI SUWARNO',
    lpjUrgent: false,
    pk: 'PK - HADI SUWARNO',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Kredit investasi alat bubut berjalan sangat baik, omzet bengkel meningkat stabil.'
  },
  {
    id: 'SURAT-082',
    nama: 'CV Sako Kencana Interior',
    tahun: '2022',
    sp1: '11-Nov-22',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV SAKO KENCANA',
    lpjUrgent: false,
    pk: 'PK - CV SAKO KENCANA',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 disampaikan, debitur telah membayar tunggakan pokok sebesar 50%.'
  },
  {
    id: 'SURAT-083',
    nama: 'Tri Wibowo (Peternakan Sapi Potong Qurban)',
    tahun: '2025',
    sp1: '05-Jan-25',
    sp1Urgent: false,
    sp2: '10-Feb-25',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - TRI WIBOWO',
    lpjUrgent: false,
    pk: 'PK - TRI WIBOWO',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Penjualan sapi musiman, debitur mengajukan skema angsuran balloon payment Idul Adha.'
  },
  {
    id: 'SURAT-084',
    nama: 'Nining Suprihatin (Kedai Makanan Khas Palembang)',
    tahun: '2023',
    sp1: '18-Feb-23',
    sp1Urgent: false,
    sp2: '24-Mar-23',
    sp2Urgent: false,
    sp3: '29-Apr-23',
    sp3Urgent: false,
    spDefault: '06-Jun-23',
    spDefaultUrgent: true,
    lpj: 'LPJ - NINING SUPRIHATIN',
    lpjUrgent: true,
    pk: 'PK - NINING SUPRIHATIN',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default telah berkekuatan hukum, debitur menyerahkan kunci ruko untuk proses lelang.'
  },
  {
    id: 'SURAT-085',
    nama: 'PT Betung Raya Transportindo',
    tahun: '2024',
    sp1: '21-Aug-24',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT BETUNG RAYA',
    lpjUrgent: false,
    pk: 'PK - PT BETUNG RAYA',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 disampaikan via pos kilat khusus, pihak manajemen PT telah menghubungi AO BRI.'
  },
  {
    id: 'SURAT-086',
    nama: 'Syahrul Gunawan (Toko Aluminium & Kaca)',
    tahun: '2022',
    sp1: '09-Jun-22',
    sp1Urgent: false,
    sp2: '14-Jul-22',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - SYAHRUL GUNAWAN',
    lpjUrgent: false,
    pk: 'PK - SYAHRUL GUNAWAN',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Kolektibilitas 3 (Kurang Lancar). Debitur diminta menghadap Kepala KCP Iskandar.'
  },
  {
    id: 'SURAT-087',
    nama: 'Marissa Haque (Apotek Berkat Sehat)',
    tahun: '2025',
    sp1: '14-Jan-25',
    sp1Urgent: false,
    sp2: '18-Feb-25',
    sp2Urgent: false,
    sp3: '24-Mar-25',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - MARISSA HAQUE',
    lpjUrgent: false,
    pk: 'PK - MARISSA HAQUE',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'SP 3 telah terbit. Pembahasan restrukturisasi terakhir sebelum penetapan default.'
  },
  {
    id: 'SURAT-088',
    nama: 'CV Talang Kelapa Mandiri',
    tahun: '2023',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV TALANG KELAPA',
    lpjUrgent: false,
    pk: 'PK - CV TALANG KELAPA',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Usaha distributor pakan ikan lele, pembayaran cicilan tidak pernah terlambat.'
  },
  {
    id: 'SURAT-089',
    nama: 'Edi Sudrajat (Toko Pancing & Jaring Ikan)',
    tahun: '2024',
    sp1: '15-Sep-24',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - EDI SUDRAJAT',
    lpjUrgent: false,
    pk: 'PK - EDI SUDRAJAT',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Surat Peringatan 1 diserahkan langsung di toko. Debitur menyanggupi bayar akhir pekan.'
  },
  {
    id: 'SURAT-090',
    nama: 'Lia Amelia (Florist & Karangan Bunga Ucapan)',
    tahun: '2022',
    sp1: '04-Apr-22',
    sp1Urgent: false,
    sp2: '09-May-22',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - LIA AMELIA',
    lpjUrgent: false,
    pk: 'PK - LIA AMELIA',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Kolektibilitas dalam pantauan khusus. Debitur berjanji melunasi 2 bulan tertunggak.'
  },
  {
    id: 'SURAT-091',
    nama: 'PT Banyuasin Samudera Perkasa',
    tahun: '2025',
    sp1: '08-Jan-25',
    sp1Urgent: false,
    sp2: '12-Feb-25',
    sp2Urgent: false,
    sp3: '16-Mar-25',
    sp3Urgent: false,
    spDefault: '20-Apr-25',
    spDefaultUrgent: true,
    lpj: 'LPJ - PT BANYUASIN SAMUDERA',
    lpjUrgent: true,
    pk: 'PK - PT BANYUASIN SAMUDERA',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default resmi, berkas kapal tongkang agunan diserahkan ke balai lelang resmi.'
  },
  {
    id: 'SURAT-092',
    nama: 'Rian Ardiansyah (Distributor Es Krim & Frozen Food)',
    tahun: '2023',
    sp1: '16-Jul-23',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - RIAN ARDIANSYAH',
    lpjUrgent: false,
    pk: 'PK - RIAN ARDIANSYAH',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'Keterlambatan karena pergantian rekening operasional. Debitur telah mengonfirmasi pembayaran.'
  },
  {
    id: 'SURAT-093',
    nama: 'Salma Hayek (Laundry Kiloan & Dry Clean)',
    tahun: '2024',
    sp1: '08-Oct-24',
    sp1Urgent: false,
    sp2: '14-Nov-24',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - SALMA HAYEK',
    lpjUrgent: false,
    pk: 'PK - SALMA HAYEK',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'SP 2 dikirim ke gerai laundry Jl. Kolonel Atmo. Debitur berjanji menyetor bunga tertunda.'
  },
  {
    id: 'SURAT-094',
    nama: 'CV Seberang Ulu Makmur',
    tahun: '2022',
    sp1: '03-Aug-22',
    sp1Urgent: false,
    sp2: '08-Sep-22',
    sp2Urgent: false,
    sp3: '15-Oct-22',
    sp3Urgent: true,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - CV SEBERANG ULU',
    lpjUrgent: false,
    pk: 'PK - CV SEBERANG ULU',
    pkUrgent: false,
    status: 'SP 3',
    catatan: 'Surat Peringatan 3. Tim recovery kredit telah memberikan somasi hukum pertama.'
  },
  {
    id: 'SURAT-095',
    nama: 'Taufik Hidayat (Toko Cat & Perlengkapan Finishing)',
    tahun: '2025',
    sp1: '-',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - TAUFIK HIDAYAT',
    lpjUrgent: false,
    pk: 'PK - TAUFIK HIDAYAT',
    pkUrgent: false,
    status: 'Lengkap / Normal',
    catatan: 'Penyaluran kredit modal kerja berjalan sangat lancar, omset toko konsisten tinggi.'
  },
  {
    id: 'SURAT-096',
    nama: 'Novianti Sari (Klinik Kecantikan & Skincare)',
    tahun: '2023',
    sp1: '20-May-23',
    sp1Urgent: true,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - NOVIANTI SARI',
    lpjUrgent: false,
    pk: 'PK - NOVIANTI SARI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 terbit, perlu peninjauan langsung kondisi terkini operasional klinik kecantikan.'
  },
  {
    id: 'SURAT-097',
    nama: 'PT Tanjung Api-Api Logistik',
    tahun: '2024',
    sp1: '11-Dec-24',
    sp1Urgent: false,
    sp2: '16-Jan-25',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT TANJUNG API-API',
    lpjUrgent: false,
    pk: 'PK - PT TANJUNG API-API',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'Fasilitas kredit modal kerja ekspor impor. SP 2 telah diterima jajaran direksi.'
  },
  {
    id: 'SURAT-098',
    nama: 'Budi Dharma (Distributor Pakan Ternak & Pupuk)',
    tahun: '2022',
    sp1: '02-Mar-22',
    sp1Urgent: false,
    sp2: '08-Apr-22',
    sp2Urgent: false,
    sp3: '14-May-22',
    sp3Urgent: false,
    spDefault: '22-Jun-22',
    spDefaultUrgent: true,
    lpj: 'LPJ - BUDI DHARMA',
    lpjUrgent: true,
    pk: 'PK - BUDI DHARMA',
    pkUrgent: false,
    status: 'SP DEFAULT',
    catatan: 'SP Default telah dieksekusi. Berkas penyerahan jaminan tanah perkebunan sudah lengkap.'
  },
  {
    id: 'SURAT-099',
    nama: 'Widya Astuti (Toko Busana Muslimah Al-Fatih)',
    tahun: '2025',
    sp1: '18-Feb-25',
    sp1Urgent: false,
    sp2: '-',
    sp2Urgent: false,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - WIDYA ASTUTI',
    lpjUrgent: false,
    pk: 'PK - WIDYA ASTUTI',
    pkUrgent: false,
    status: 'SP 1',
    catatan: 'SP 1 diterbitkan sebagai peringatan awal masa grace period pokok kredit.'
  },
  {
    id: 'SURAT-100',
    nama: 'PT Sriwijaya Energi Nusantara',
    tahun: '2024',
    sp1: '05-Sep-24',
    sp1Urgent: false,
    sp2: '12-Oct-24',
    sp2Urgent: true,
    sp3: '-',
    sp3Urgent: false,
    spDefault: '-',
    spDefaultUrgent: false,
    lpj: 'LPJ - PT SRIWIJAYA ENERGI',
    lpjUrgent: false,
    pk: 'PK - PT SRIWIJAYA ENERGI',
    pkUrgent: false,
    status: 'SP 2',
    catatan: 'SP 2 aktif. Debitur dijadwalkan mediasi khusus restrukturisasi kredit bersama pimpinan cabang.'
  }
]

// Gabungkan 35 data lama + 65 data baru = 100 data
const full100List = [...existing35, ...additionalData]

console.log(`Total data setelah digabung: ${full100List.length} surat`)

// 3. Tulis ke file src/data/initialSuratData.js
const fileContent = `// Data Dummy Simulasi Arsip Surat Debitur BRI KCP Iskandar Palembang
// Dibuat khusus untuk keperluan demo, presentasi laporan akhir magang, dan portofolio agar data riil nasabah terlindungi (Privasi & Rahasia Bank).
// Total: 100 Arsip Surat (SURAT-001 s.d. SURAT-100)

export const initialSuratList = ${JSON.stringify(full100List, null, 2)}
`

const targetPath = path.resolve(__dirname, '../src/data/initialSuratData.js')
fs.writeFileSync(targetPath, fileContent, 'utf-8')
console.log('✅ File src/data/initialSuratData.js berhasil diperbarui dengan 100 data surat!')

// 4. Upload langsung ke Supabase
const url = 'https://yershpucmwqmgprblnac.supabase.co'
const key = 'sb_publishable_xxgvJajfTNCLo_UcjaGqiA_5KlsSAOD'
const supabase = createClient(url, key)

const toDbRow = (item) => ({
  id: item.id,
  nama: item.nama,
  tahun: item.tahun,
  sp1: item.sp1 || '-',
  sp1_urgent: Boolean(item.sp1Urgent),
  sp2: item.sp2 || '-',
  sp2_urgent: Boolean(item.sp2Urgent),
  sp3: item.sp3 || '-',
  sp3_urgent: Boolean(item.sp3Urgent),
  sp_default: item.spDefault || '-',
  sp_default_urgent: Boolean(item.spDefaultUrgent),
  lpj: item.lpj || '-',
  lpj_urgent: Boolean(item.lpjUrgent),
  pk: item.pk || '-',
  pk_urgent: Boolean(item.pkUrgent),
  status: item.status || 'Lengkap / Normal',
  catatan: item.catatan || ''
})

async function uploadToSupabase() {
  console.log('Mengupload 100 data ke tabel surat_debitur di Supabase...')
  const dbRows = full100List.map(toDbRow)

  // Upsert in batches of 50
  for (let i = 0; i < dbRows.length; i += 50) {
    const chunk = dbRows.slice(i, i + 50)
    const { error } = await supabase.from('surat_debitur').upsert(chunk, { onConflict: 'id' })
    if (error) {
      console.error(`❌ Error upload batch ${i} - ${i + chunk.length}:`, error.message)
    } else {
      console.log(`✅ Batch ${i + 1} - ${i + chunk.length} berhasil diupload`)
    }
  }

  // Verifikasi jumlah akhir di Supabase
  const { count, error: countErr } = await supabase
    .from('surat_debitur')
    .select('id', { count: 'exact', head: true })
  
  if (!countErr) {
    console.log(`🎉 Total data surat di Supabase saat ini: ${count} surat!`)
  }
}

uploadToSupabase()
